// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56_mGFYjg9v5Ndm9ERFKQMMtWDORADmg',
    appId: '1:104685050302:web:22e9c7dd18f36d3c8601ef',
    messagingSenderId: '104685050302',
    projectId: 'studymate-c999f',
    authDomain: 'studymate-c999f.firebaseapp.com',
    storageBucket: 'studymate-c999f.firebasestorage.app',
    measurementId: 'G-M3KJM7HQJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMY2-aN09uv4JYbKOqsUCdEEEmKlROCV8',
    appId: '1:104685050302:android:35a81b30ace545e58601ef',
    messagingSenderId: '104685050302',
    projectId: 'studymate-c999f',
    storageBucket: 'studymate-c999f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGN-yEBhmXf_OBHcaBierZJ8foY4d_INI',
    appId: '1:104685050302:ios:25ab23e4cd96045f8601ef',
    messagingSenderId: '104685050302',
    projectId: 'studymate-c999f',
    storageBucket: 'studymate-c999f.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGN-yEBhmXf_OBHcaBierZJ8foY4d_INI',
    appId: '1:104685050302:ios:25ab23e4cd96045f8601ef',
    messagingSenderId: '104685050302',
    projectId: 'studymate-c999f',
    storageBucket: 'studymate-c999f.firebasestorage.app',
    iosBundleId: 'com.example.studymate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB56_mGFYjg9v5Ndm9ERFKQMMtWDORADmg',
    appId: '1:104685050302:web:6eec7790573e95eb8601ef',
    messagingSenderId: '104685050302',
    projectId: 'studymate-c999f',
    authDomain: 'studymate-c999f.firebaseapp.com',
    storageBucket: 'studymate-c999f.firebasestorage.app',
    measurementId: 'G-FBS23CH5C8',
  );
}
